# Математика для машинного обучения
## Домашнее задание №3

_Автор задания: Илья Щуров_

Подготовлено для программы «[Практический анализ данных и машинное обучение](https://cs.hse.ru/dpo/bigml)» (ФКН НИУ ВШЭ).

Задание выполнил(а): *(впишите сюда фамилию и имя)*

### О задании

В задании встречаются задачи трёх видов. Обычные задачи — чаще всего, простые задачи на определения. Их нужно сделать, если понятия, обсуждавшиеся на лекции, кажутся вам новыми или прочно забытыми. Задачи со звёздочкой — на доказательства. Их можно пропустить, если вы проходите этот материал впервые, но они помогут разобраться в нём глубже. Они также не являются сложными при наличии некоторой математической подготовки. Наконец, задачи с двумя звёздочками — для тех, кто имеет математическое образование.

Вы можете выбрать, какой тип задач вы хотите решать — скорее всего, если вы можете решить задачи со звёздочкой, то задачи без звёздочек будут для вас слишком простыми (но может быть и нет — в любом случае, просмотрите их и поймите, являются ли они для вас совсем устными; если нет — лучше сделайте их).

Все задачи выбранного типа необходимо решить к 23:59:59 дня, следующего за днём следующего занятия. (В данном случае — к вечеру среды.)

## Линейная алгебра — 3
**Определение.** *Линейным подстространством* называется такое подмножество $V\subset \mathbb R^n$ линейного пространства, что для любых двух векторов из $V$ любая их линейная комбинация лежит в $V$. Иными словами, для любых $u, v \in V$ и $\lambda, \mu \in \mathbb R$, $\lambda u + \mu v \in V$.


### Задача 1
Являются ли следующие множества линейными подпространствами? Если да, докажите. Если нет, обоснуйте.

0. Множество всевозможных векторов $u=(u_1, u_2, u_3) \in \mathbb R^3$, таких, что $u_1 = u_2$?
1. Множество всевозможных векторов $u=(u_1, u_2, u_3) \in \mathbb R^3$, таких, что $u_1 = u_2 = 2 u_3$?
2. Множество всевозможных векторов $u=(u_1, u_2, u_3) \in \mathbb R^3$, таких, что $u_1 = u_2^2$ (здесь $u_2^2$ — это квадрат $u_2$)?
3. Множество всевозможных векторов $u=(u_1, u_2, u_3) \in \mathbb R^3$, таких, что $u_1 = u_2 + 1$?

*(впишите решение сюда)*

Пусть матрица $A$ имеет $m$ строк и $n$ столбцов. Тогда она задаёт отображение из $\mathbb R^n$ в $\mathbb R^m$.

**Определение.** *Образом (image)* отображения, заданного матрицей $A$, называется множество векторов $u \in \mathbb R^m$, обладающих следующим свойством: найдётся такой вектор $v \in \mathbb R^n$, что $Av = u$. Иными словами, образ — это множество тех векторов, в которые мы можем «попасть», действуя отображением с матрицей $A$.

**Определение.** *Ядром (nullspace)* отображения, заданного матрицей $A$, называется множество векторов $v \in \mathbb R^n$, отображаемых матрицей $A$ в нулевой вектор:

$$\ker A = \{v \in \mathbb R^n\mid Av = 0\}.$$

**Теорема.** Образ и ядро являются линейными подпространствами. Сумма их размерностей равна $n$.

**Определение.** *Рангом* матрицы $A$ называется размерность образа соответствующего отображения.

**Утверждение.** Ранг матрицы можно вычислить как максимальное число линейно независимых столбцов или максимальное число линейно независимых строк (эти два числа всегда совпадают).

### Задача 2
Найти ядро отображения, заданного матрицей. Найти ранг этой матрицы.

$$
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
1 & 0 & -1
\end{pmatrix}
$$

Вы можете попробовать выполнить это задание вручную, а затем проверить, что нашли ранг правильно, с помощью `numpy.linalg.matrix_rank`.

*(впишите решение сюда)*

### Задача 3 (*)
*Внешним произведением* векторов $u=(u_1,\ldots, u_n)\in \mathbb R^n$ и $v=(v_1,\ldots, v_n)$ называется матрица $uv^T$:

$$
\begin{pmatrix}
u_1 \\
u_2 \\
\vdots \\
u_n
\end{pmatrix}
\begin{pmatrix}
v_1 & v_2 & \cdots & v_n
\end{pmatrix}
$$

Найти её ранг.

*(впишите решение сюда)*

**Определение.** *Обратной матрицей* к квадратной матрице $A$ называется такая матрица $A^{-1}$, что $A^{-1}A=AA^{-1}=E$, где $E$ — единичная матрица (такая матрица, у которой на диагонали стоят единицы, а все остальные элементы нулевые). Обратная матрица соответствует обратному отображению: если взять вектор $y=Ax$, являющийся образом вектора $x$ под действием матрицы $A$, и подействовать на него матрицей $A^{-1}$, то получится снова вектор $x$. Матрица является обратимой (невырожденной) тогда и только тогда, когда её ранг максимален (равен числу строк или столбцов).

### Задача 4
Найти без использования компьютера обратную матрицу к матрице $A$. (Понять, как действует матрица $A$ на плоскость, придумать обратное действие и найти его матрицу.)

$$
A=\begin{pmatrix}
0 & -2 \\
2 & 0
\end{pmatrix}
$$

*(впишите решение сюда)*

### Задача 5 (*)
Вася решает систему линейных уравнений следующего вида:

$$
\left\{
\begin{align}
x_1 + 2 x_2 & = b_1 \\
x_2 + 2 x_3 & = b_2 \\
\vdots \\
x_{n-1} + 2 x_{n} & = b_{n-1} \\
x_n & = b_n
\end{align}
\right.
$$

1. Записать эту систему в матричной форме. Выписать матрицу $A$ системы.
2. Для $n=100$ найти с помощью компьютера обратную матрицу к матрице $A$. 
3. Вася хотел решить эту систему с правой частью $b_1 = b_2 = \ldots = b_n = 0$. Но когда Вася отвернулся, Петя подменил правую часть, добавив к каждому $b_k$ маленькое число $10^{-10}$, $k=1, \ldots, n$. Вася не заметил подвоха и стал решать систему с такой правой частью. Какова норма разности между правильным ответом и ответом, который в результате получил Вася?

**Подсказка.** Для генерирования матрицы $A$ можно использовать функцию `np.diag`, для вычисления обратной матрицы — `scipy.linalg.inv`, для нахождения нормы вектора — `scipy.linalg.norm`.

In [65]:
import numpy as np
print(np.diag([1, 2, 3]))
print(np.diag([2] * 5)) # можно умножить список на число чтобы повторить его несколько раз
print(np.diag([3] * 4, 1)) # второй параметр отвечает за выбор диагонали

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[2 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 2]]
[[0 3 0 0 0]
 [0 0 3 0 0]
 [0 0 0 3 0]
 [0 0 0 0 3]
 [0 0 0 0 0]]


*(впишите решение сюда)*

### Задача 6
С помощью `numpy` найти собственные векторы и собственные значения следующей симметричной матрицы. Убедиться в том, что собственные векторы, соответствующие разным собственным значениям, ортогональны.

$$
B = \begin{pmatrix}
1 & 2 & 3 \\
2 & 5 & 1 \\
3 & 1 & 8 \\
\end{pmatrix}
$$

*(впишите решение сюда)*

### Задача 7 (*)
Написать код, который для заданной матрицы 2×2 $A$ рисует образ единичной окружности под действием оператора, заданного этой матрицей, и два собственных вектора матрицы $AA^T$. Убедиться в том, что оси получающегося эллипса совпадают с этими собственными векторами.

In [6]:
# (впишите решение сюда)

### Задача 8 (**)
Доказать, что оси эллипса из предыдущей задачи всегда будут совпадать с собственными векторами матрицы $AA^T$.

In [7]:
# (впишите решение сюда)